### PR TITLE
add scipy scikit-learn to Galaxy

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @tnabtaf and @jgoecks 
Not sure if this fits here, but happy to contribute it for the blogs before we try to publish it.

**Comment by tnabtaf** [comment]
@bgruening I'll review the text.  Any chance I can convince you that this can go out next Monday night/Tuesday morning instead of this Wednesday/Thursday?  I'm trying to space things out a little.

**Comment by tnabtaf** [comment]
@bgruening I did a little bit of editing.  Please let me know bout the date change.

**Comment by bgruening** [comment]
@tnabtaf sure, whenever this fits your schedule. This announcement has time.

**Comment by tnabtaf** [comment]
@bgruening Thanks.  I'll merge and post this on Monday.  I'll update dates and path names to reflect that.

**Pull request merged**
