### PR TITLE
Revamp french community pages + add annotation community of practice

### PR DESCRIPTION
**Pull request by abretaud**
- Removed GenOuest and BIPAA servers and pages as we're closing them in favor or usegalaxy.fr
- Revamped the elixir-fr page as it was outdated
- Added genome annotation community of practice

Setting as draft to let other people have a look before merging

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
The failing test is from single-cell domain and would need a fix. Not strictly this PR.

**Comment by abretaud** [comment]
I can fix it, but not sure what you wanted to do at https://github.com/galaxyproject/galaxy-hub/blob/master/content/projects/singlecell/index.md?plain=1#L71 @nomadscientist :grimacing:

**Comment by nomadscientist** [comment]
Um, well, given I don't actually understand what's broken I can't exactly fix it! Is it just the calendar embed is being weird?  What do I need to do?

**Comment by nomadscientist** [comment]
OK! I think I fixed them

**Comment by abretaud** [comment]
oh ah, "chips", we fixed at the same time :D

**Comment by abretaud** [comment]
Where's your fix? Maybe I can pull it to make things easier
("chips" = "jinx" in english apparently)

**Comment by nomadscientist** [comment]
Hah that's good to know, chips indeed!
I just tried to update the links to these, idk why they were so weird:

https://calendar.google.com/calendar/embed?src=galaxy.sc.cop%40gmail.com&ctz=Europe%2FLondon

https://calendar.google.com/calendar/ical/galaxy.sc.cop%40gmail.com/public/basic.ics

**Pull request merged**
