### PR TITLE
Clean up toolshed wiki pages.

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by martenson** [comment]
we agreed with @davebx that this also needs a list of redirects/rewrites for dropped/rewritten urls

**Comment by dannon** [comment]
Good, I was just writing an email about that :)

Let's have that go live around the same time this gets merged (not yet, would like to review still), so we don't float borken links out there.

**Comment by tnabtaf** [comment]
Hi All,

What's that status on this?  I can review if needed.

**Comment by dannon** [comment]
I glanced over it and it seemed good to me, just waiting on those redirects I think.  Unless I missed that happening.

**Comment by martenson** [comment]
@dannon I have the redirects ready, will run them after merge

**Comment by dannon** [comment]
Works for me.  @tnabtaf seem good to go?

**Comment by martenson** [comment]
all rewrites are in place
https://github.com/galaxyproject/infrastructure-playbook/commit/e8353672357a651d80e1ef562a4346718dbeb9fa

**Pull request merged**
