### PR TITLE
News item for pulsar deployment with Infrastructure Manager

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Pending: upload video recording and add the link below.

### CODE REVIEW

**Comment by bgruening** [comment]
Maybe that helps for embedding the video: https://github.com/galaxyproject/galaxy-hub/blob/0324ac15f097e724bfe622637fddfbf0552e6684/content/news/2023-03-15-new-history-search/index.md?plain=1#L81

**Comment by sebastian-luna-valero** [comment]
Hi @bgruening  

If you don't have a Youtube channel, we can use the [EGI](https://www.youtube.com/@EGI_eInfra/videos) one and embed the video from there.

We will also reuse this for a news item in EGI.

Please let me know your preferences.

Thanks,
Sebastian

**Comment by dannon** [comment]
Video is still processing for HD, but it'll be available here shortly:  https://youtu.be/5EMXzD_JDjw

**Comment by bgruening** [comment]
Thanks @dannon! We can use the <video> tag also for youtube links isn't it?

**Comment by dannon** [comment]
Most of the youtube embeds use an iframe -- that's what I'd do here.  The <video> embeds were for hub-hosted files IIRC.

**Pull request merged**
