### PR TITLE
Strip NWWLs

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by dannon** [comment]
@VJalili This should fix them all up in one pass.

**Comment by VJalili** [comment]
Thank you @dannon. Actually I was looking for what could be the "working" link for `<<nwwl(POST)>>`. It seems, it's just `POST`--no link.

**Comment by dannon** [comment]
Yep, I think that's right.  The nwwl was preventing moinmoin from making links, so this should handle it.  Thanks for taking a look and bringing this up!

**Comment by VJalili** [comment]
You're welcome :)
It looks better now, as `<<nwwl...>>`'s were misleading. Thanks !

**Pull request merged**
