### PR TITLE
Basic eventzilla embed

### PR DESCRIPTION
**Pull request by dannon**
Adds an eventzilla embed component that takes an event id and injects everything it needs.

Shows up something like this:

image

### CODE REVIEW

**Comment by afgane** [comment]
@dannon, we have an early version of the GCC schedule so it's getting to be time to merge this. I'm not confident in resolving the conflicts so could you please take a look?

**Comment by dannon** [comment]
@afgane Resolved; it just needs to be included wherever you want it to show up like was in https://github.com/galaxyproject/galaxy-hub/pull/1900/commits/52389502d07a3aa990804c4ee7a2a4f948a74994, but with the right event id.

**Comment by afgane** [comment]
Excellent! Thank you. Let me check with Jenn if she imported the schedule yet and I can then add the event ID.

**Comment by dannon** [comment]
Sounds good.  I'll go ahead and merge the component in, and it can be added to a page whenever.

**Pull request merged**
