### PR TITLE
fix gcc24 links

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @martenson, but something is failing here. Can you please have a look?

**Comment by martenson** [comment]
a bunch of ` CypressError: Timed out after waiting `60000ms` for your remote page to load.`; restarted tests

**Comment by bgruening** [comment]
It might be plausible again, we are working on this.

**Comment by martenson** [comment]
this is safe to merge, we are sending traffic to these pages and they should have good links

**Pull request merged**
