### PR TITLE
Jupyterlabs tools of earth-system

### PR DESCRIPTION
**Pull request by Marie59**
add some info on what's new on earth system subdomain

### CODE REVIEW

**Comment by bgruening** [comment]
@Marie59 I added some spelling fixes and moved some words around, can you please check?

Thanks a lot for writing this up!

**Comment by Marie59** [comment]
Yes everything seems good to me ! I am just not sure about the commas that you put before the "and" ? And I don't understand the new error in the checks

**Comment by bgruening** [comment]
I think its called Oxford comma (https://www.scribbr.com/commas/oxford-comma/). The failing test was just a glitch in the matrix.

**Comment by bgruening** [comment]
Thanks! Hope you had a nice trip back.

**Comment by Marie59** [comment]
Waouh thanks for the review and comma tip ;) Yes everything perfect on my side ! Have a nice sail ;)

**Pull request merged**
