### PR TITLE
Authentication and authorization documentation page

### PR DESCRIPTION
**Pull request by VJalili**

### CODE REVIEW

**Comment by martenson** [comment]
Could we please move this to a full url without abbreviation? For SEO purposes.

**Comment by VJalili** [comment]
Are you referring to `authnz`?

**Comment by martenson** [comment]
>Are you referring to authnz?
yes

**Comment by VJalili** [comment]
_authnz_ stands for _Authentication and Authorization_, but I'm not sure such a long name would be appropriate here. So, I renamed to _authentication_, which should be comprehensive enough for now.

**Comment by martenson** [comment]
lgtm - thanks for writing docs! 

I do not plan to merge this until the PR is merged. Additionally this might be a good candidate to be moved to the codebase (i.e. docs.galaxyproject.org) since I assume this will evolve over releases. What do you think?

**Comment by VJalili** [comment]
I don't think documenting a work in the PR is good place, mainly because it is not intuitive for someone who wants to use a feature, and cares less for how it is implemented. So, this PR serves two purposes: (1) explain how to test that PR, (2) explain how to use this future for potential end-users and admins. 

Incidentally, authentication and authorization is just started with that PR and will evolved significantly. Accordingly, this documentation will evolve covering newer concepts. 

I guess we could merge this once that PR is merge.

**Comment by martenson** [comment]
I think https://docs.galaxyproject.org/en/master/admin/authentication.html is a great place for it. I am not suggesting to document in a PR. Thats @jmchilton's area :)

**Comment by VJalili** [comment]
Are galaxyhub and docs same/mirror?

**Comment by martenson** [comment]
No, docs are tightly coupled with the code and generated from the main Galaxy repo (https://github.com/galaxyproject/galaxy/blob/dev/doc/source/admin/authentication.md)

Hub is a wiki and its source is this repo.

**Comment by VJalili** [comment]
Sounds good. At the moment, this documentation is mainly user-oriented (how to use it), so I guess this hub is probably a good choice. We could also have some developer-friendly documentation in that docs in future.

**Comment by martenson** [comment]
This is a WIP since the functionality is not merged yet. I will merge this once https://github.com/galaxyproject/galaxy/pull/4474 is merged

**Comment by martenson** [comment]
Done, ready for review.

**Comment by tnabtaf** [comment]
@VJalili Can I suggest that `config.md` be moved into `/src/admin/authentication/config/index.md` ?  I believe that parts of the infrastructure count on everything being in an `index.md`.

**Comment by martenson** [comment]
thanks for the docs, I still think the admin part should be reflected here: https://docs.galaxyproject.org/en/master/admin/authentication.html

**Comment by VJalili** [comment]
Thanks @martenson, I'll update that admin documentation too.

**Pull request merged**
