### PR TITLE
Redesign Homecards: light theme

### PR DESCRIPTION
**Pull request by NickSto**
This gives the homecards (the panels on the front page) an overdue due redesign.

I basically ripped off the look of the cards on the .eu homepage because they look way better.

Feedback is welcome!

image

### CODE REVIEW

**Review by beatrizserrano — APPROVED** [review]
Looks good to me, Nick! This style definitely fits better, thanks. 
The only thing that bothers me a bit is the different widths. I think that what fails is the cards with the profiles, I don't know how to make them wider.
image

**Comment by NickSto** [comment]
@beatrizserrano Okay, I've tweaked the cards so their row is *nearly* the same width as the columns below. It's tricky to get it exact, but maybe this is close enough?

image

**Comment by beatrizserrano** [comment]
> @beatrizserrano Okay, I've tweaked the cards so their row is *nearly* the same width as the columns below. It's tricky to get it exact, but maybe this is close enough?

Yes :) Thanks for finding a solution!

**Comment by dannon** [comment]
I'm tinkering with a few options here and I think it's easier to read and less cluttered if we just drop the borders everywhere.  What do folks think?

Before:
image


After:
image

**Comment by NickSto** [comment]
@dannon Hmm that's a toughie. I tend to like the defined panels, but I'm no designer so I wouldn't weight that opinion heavily.

**Comment by beatrizserrano** [comment]
Maybe just the outer border would work? i.e. separation between boxes but not between items. That would be an intermediate way of presenting it

**Comment by dannon** [comment]
@beatrizserrano Sure, let me mock that one up

**Comment by NickSto** [comment]
Still hard to tell for me. I think I like this more than no borders at all, personally.

**Comment by beatrizserrano** [comment]
Yes, I like it more, too! Thanks, @dannon and @NickSto :)

**Comment by dannon** [comment]
@beatrizserrano Okay, cool.  Let me push that to this branch and then we can get this in!  We can always continue to iterate, of course.

**Comment by NickSto** [comment]
Looks good to me. I'm ready to merge.

**Comment by NickSto** [comment]
Man, it feels so much better to go to the homepage and see this instead now.

**Pull request merged**
