### PR TITLE
Usegalaxy fr

### PR DESCRIPTION
**Pull request by lecorguille**
Add usegalaxy.fr in the instance list

### CODE REVIEW

**Comment by tnabtaf** [comment]
@lecorguille I just became aware that this server was available a week ago.  We need to have a big announcement about this!  **Big!**  (I have been trying to find time...)

**Comment by lecorguille** [comment]
@tnabtaf 😄 

Indeed, this instance aims to gather different French laboratory or thematic instances (including Workflow4Metabolomics and ProteoRE) into one single main point.
usegalaxy.fr have also been installed from scratch following the some of the usegalaxy.* mechanims (Ansible, Git/CI, community managment ...).

**Comment by yvanlebras** [comment]
Great news! It will be a pleasure to see ecology tools on it too ;) don't hesitate to ping me Gildas

**Comment by lecorguille** [comment]
@yvanlebras , with pleasure!
But, for you, I guess we still need to set up the Integrative Tools. We are on it with Anthony since this week.

**Comment by yvanlebras** [comment]
Yes, it will be top to have IT. but waiting for that, it can be cool to have ecology tools. Happy to see usegalaxy.fr is out!

**Pull request merged**
