### PR TITLE
OIDC Elixir AAI user and admin docs

### PR DESCRIPTION
**Pull request by kjellp**
This PR contains proposed user documentation for using Elixir AAI, and admin documentation for registering a Galaxy server with the Elixir AAI service as well as configuring the Galaxy server itself. I've also added links to the new OIDC backend in the OIDC generic pages were relevant.

### CODE REVIEW

**Comment by bgruening** [comment]
@kjellp https://github.com/galaxyproject/galaxy-hub/blob/master/CONTRIBUTING.md#setup

**Comment by VJalili** [comment]
@kjellp regarding last couple of commits, do you prefer to rebase or a squash merge?

**Comment by kjellp** [comment]
@VJalili I've done new screenshot uploads using git-lfs. (Thought I could avoid it, but was simpler to do then I expected/feared). Not happy with all the individual commits, but they were generated using the GitHub UI.
I'm not to familiar with the rebasing, was reading up on that when I saw your latest comment. Don't think to keep the commit history is that important, all is simply "the initial commit", so anyway you prefer to merge it without messing up the overall commit history is fine for me.

**Comment by kjellp** [comment]
@VJalili I think I've successfully completed a rebase to have the fork in sync with the upstream base.

**Comment by VJalili** [comment]
@kjellp I made a PR to your branch, it should do the rebase.

**Comment by kjellp** [comment]
@VJalili I'm happy to merge your PR if that solves the problem.

Did you see my previous comment about the upstream sync I already did? Is
your rebase PR still needed?

If so, which of the three merge options GutHub provides me with:
1 - merge commit
2 -  squash commit
3 - rebase commt
yields the desired result? The third one?

tir. 30. apr. 2019, 20:58 skrev Vahid <notifications@github.com>:

**Comment by VJalili** [comment]
Yes, I saw your comment and new PR. My rebase squashes your latest commits into one hence removing them from history. You can use either of the options to merge my PR, maybe you can use just "merge commit".

**Comment by kjellp** [comment]
Done now!


tir. 30. apr. 2019, 21:52 skrev Vahid <notifications@github.com>:

**Comment by VJalili** [comment]
Thank you, I used `git rebase -i b0c0cc0ea765a839543f73a0880faa0dcf248311` with `f` option for all subsequent commits, though I think it did not fix the history. I will just squash merge this one then.

**Comment by VJalili** [comment]
@kjellp Thank you for the docs :)

**Comment by kjellp** [comment]
@VJalili happy to contribute!

tir. 30. apr. 2019, 22:03 skrev Vahid <notifications@github.com>:

**Pull request merged**
