### PR TITLE
Added missing links.

### PR DESCRIPTION
**Pull request by VJalili**
The missing links to `Main` and `Test` are added.

### CODE REVIEW

**Comment by martenson** [comment]
These are probably supposed to go to https://galaxyproject.org/main/ and https://galaxyproject.org/test/ respectively.

**Comment by VJalili** [comment]
Thanks for mentioning it.

**Comment by martenson** [comment]
@VJalili These should point to `/src/main/index.md` and `/src/test/index.md` respectively. It makes the whole hub portable and editing in github easier.

**Comment by VJalili** [comment]
Sorry, I have committed before you edited your comment.

**Comment by martenson** [comment]
@VJalili thanks

**Pull request merged**
