### PR TITLE
updated teaser for the call of contribution

### PR DESCRIPTION
**Pull request by teresa-m**
updated the teser. Here was a copy past issue. Hope it is now all corrct. 

@Delphine-L: It would be great if you can check the news post about the open call for trainers. Is everthing understandable?

### CODE REVIEW

**Comment by teresa-m** [comment]
Could someone please mearge the updates to the blogpost. Thanks a lot!

**Comment by bebatut** [comment]
There is a conflict on the file. Can you revolve it?

**Review by dannon — APPROVED** [review]

**Comment by dannon** [comment]
Test failure is the timeout again, I thought we had this resolved but I'll see what we can do -- no worries here though.

**Comment by teresa-m** [comment]
Thanks a lot!

**Pull request merged**
