### PR TITLE
Add job listing to the Galactic Career Center

### PR DESCRIPTION
**Pull request by natwhitaker**
Adding "Genomics Education Lead - Assistant Research Scientist" job posting to the Galactic Career Center on behalf of Dr. Frederick Tan.

### CODE REVIEW

**Comment by natwhitaker** [comment]
@tcollins2011 Hi Tyler! Would you mind checking this for me? I haven't updated the Galactic Career Center before and just want a second set of eyes.

**Comment by dannon** [comment]
@natwhitaker I can take a look if you'd like, but the tests pass -- were you able to run this locally to see if it looks how you want?

**Comment by dannon** [comment]
image

**Comment by natwhitaker** [comment]
@dannon I was just noticing some issues with some links (emails, for example) and thought maybe I was doing something wrong. But I also see that some past postings have similar issues, so I've just made some changes to make it look cleaner. If these pass, I'll move it on through. Thanks for the help!

**Comment by dannon** [comment]
Sure.  I fixed the link, I'll go ahead and merge this.

**Pull request merged**
