### PR TITLE
Simple public servers json feed.

### PR DESCRIPTION
**Pull request by dannon**
Suuuuuuper minimal example of what a public servers JSON feed would look like.  Will refine more in the morning.  (xref a thread w/ @tnabtaf, @erasche, @martenson)

Instead of an exclusion list, we should pick which elements we care to include and use that.  It should also (obviously) generate a .json file and set headers correctly, instead of .html.  This is a good starting point, though.

### CODE REVIEW

**Comment by erasche** [comment]
Why omit any information? Why not include it all?

**Comment by dannon** [comment]
@erasche Yep, metalsmith internal information like file size, template layout, etc.

**Comment by dannon** [comment]
Tossing an update here before I forget it -- metalsmith-headings-identifiers is mangling the contents of the stream, so we'll want to fix that before merging this.  m-h-i is also slow, and I think we can roll the functionality it provides into the marked renderer pretty easily.

**Comment by dannon** [comment]
The identifiers bit is fixed with #336, after which we can merge and move forward with this.

**Pull request merged**
