### PR TITLE
added news about two talks at NeIC 2024

### PR DESCRIPTION
**Pull request by teresa-m**

### CODE REVIEW

**Comment by teresa-m** [comment]
@sanjaysrikakulam: if you want to have a look.

**Comment by sanjaysrikakulam** [comment]
> @sanjaysrikakulam: if you want to have a look.

Thanks! Everything looks fine from my side. I adjusted the formatting.

**Comment by bgruening** [comment]
Please take it out of Draft if its ready.

**Comment by teresa-m** [comment]
Yes, It is ready but again there are timeout errors. But nothing for me to fix?

**Comment by bgruening** [comment]
I also don't understand the errors. I restarted it but it still failed. Dannon, is that the PR or something in the built infrastructure?

**Comment by dannon** [comment]
@bgruening When you visit https://plausible.galaxyproject.eu/ is it responsive?  It's not for me and that's the root of this.

I am adding a cypress intercept to ignore this, though, so it won't matter if it's up or not moving forward.

**Comment by bgruening** [comment]
Yes, this can be I just assumed you fixed that already. We had this problem already I thought. I'm getting old :)

Thanks for fixing it.

**Comment by dannon** [comment]
@bgruening I thought the previous change fixed it as well, actually, but maybe it just coincided with you guys getting it back online and we all thought it was fine for a while?

**Comment by dannon** [comment]
Sorry for the trouble @teresa-m, the tests will be more robust moving forward after #2656.

**Comment by bgruening** [comment]
Thanks Dannon!

**Pull request merged**
