### PR TITLE
Fix invalid date (BGE job offer)

### PR DESCRIPTION
**Pull request by abretaud**

### CODE REVIEW

**Comment by abretaud** [comment]
I think the url has several redirections, maybe the error comes from that?

**Comment by bgruening** [comment]
Yes, I assume so :(

**Comment by bgruening** [comment]
@dannon this is new :(

```

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/galaxy-hub/galaxy-hub/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/galaxy-hub/galaxy-hub/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/runner/work/galaxy-hub/galaxy-hub/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/runner/work/galaxy-hub/galaxy-hub/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/runner/work/galaxy-hub/galaxy-hub/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/runner/work/galaxy-hub/galaxy-hub/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/runner/work/galaxy-hub/galaxy-hub/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/runner/work/galaxy-hub/galaxy-hub/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/runner/work/galaxy-hub/galaxy-hub/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/runner/work/galaxy-hub/galaxy-hub/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/runner/work/galaxy-hub/galaxy-hub/node_modules/cache-loader/dist/index.js:118:7
    at /home/runner/work/galaxy-hub/galaxy-hub/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by dannon** [comment]
@bgruening Thanks for the ping, I'll check it out.  I'm surprised this popped up in CI, though, unless the node version changed under us.

**Pull request merged**
