### PR TITLE
usegalaxy.eu use cases 2024: Blog post of Ali Sajid Imami

### PR DESCRIPTION
**Pull request by sebastian-schaaf**
Draft article, requires update and author's final confirmation

### CODE REVIEW

**Comment by sebastian-schaaf** [comment]
Awaiting (and expecting) green lights by the author.

**Comment by bgruening** [comment]
Any update here?

**Comment by sebastian-schaaf** [comment]
Final reminder email sent to author - I cc'd you

Am Di., 2. Juli 2024 um 21:18 Uhr schrieb Björn Grüning <
***@***.***>:

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
