### PR TITLE
Fix typo for PlantTribes tutorial

### PR DESCRIPTION
**Pull request by gregvonkuster**
Sorry I missed this typo in my initial commit!

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @gregvonkuster!

**Comment by nekrut** [comment]
@gregvonkuster : this tutorial cannot be listed under "Tutorials using Galaxy Main" since these tools are not on main. Please, create a special section for this instance and move it there.

**Comment by gregvonkuster** [comment]
@nekrut sure!  What should the section be labeled?

**Comment by gregvonkuster** [comment]
@martenson or @blankenberg or @dannon or @nekrut I'm hoping these tools will eventually be available on main, but in the meantime to what section on the page would you advise this PlantTribes tutorial be moved?  Should I create a new section - if so, what should the label be?  Or should I move it to another existing section?  Thanks!

**Comment by martenson** [comment]
@gregvonkuster Probably a new section? Does not seem to fit any existing imo. Maybe GTN section as alternative.

**Comment by gregvonkuster** [comment]
Yeah, I'll wait a bit longer and move it to the GTN if no additional responses.  I don't know what the new category label should be if we go that route.  Perhaps "Coming soon to main" or something similar?

**Pull request merged**
