### PR TITLE
Updated nginx configuration descriptions 

### PR DESCRIPTION
**Pull request by VJalili**
Added some missing info for SSL configuration on nginx, fixed some types, and updated text for clarity.

### CODE REVIEW

**Comment by dannon** [comment]
@VJalili one more change that I think would bring it inline with the other naming conventions would be to move it from `nginxProxy` to `nginx-proxy`

**Comment by VJalili** [comment]
@dannon good idea; I renamed the folder.

**Comment by martenson** [comment]
@VJalili you renamed it using underscore as opposed to dash. 

Also renaming should follow the advice about redirects [here](https://github.com/galaxyproject/galaxy-hub#redirects) - now the links to this page are broken.

**Comment by VJalili** [comment]
Thanks @martenson; please see [this PR](https://github.com/galaxyproject/galaxy-hub/pull/243)

**Comment by dannon** [comment]
Good catch @martenson, and thanks for the update @VJalili.

**Pull request merged**
