### PR TITLE
Swap to my fork of metalsmith-autotoc for about 1000% faster autotoc'…

### PR DESCRIPTION
**Pull request by dannon**
… for about 1000% faster autotoc'ing.

Note that this is a temporary swap, pending merge of https://github.com/anatoo/metalsmith-autotoc/pull/6, at which point we can remove it.

### CODE REVIEW

**Comment by dannon** [comment]
xref #240 

@tnabtaf Care to check this out and see if it all still looks right?

**Comment by dannon** [comment]
(WIP'ing it, looks like there may be an issue handling context)

**Comment by dannon** [comment]
Yeah, fixed that :)  Ready for review.

**Comment by jxtx** [comment]
Ping @nekrut

**Comment by bgruening** [comment]
Cool beans! Thanks @dannon!

**Pull request merged**
