### PR TITLE
ESG WP5 astronomy FITS

### PR DESCRIPTION
**Pull request by volodymyrss**
@francoismg and myself made this post following suggestion of @bgruening .

Please let us know what you think!
Also, there is a question inside about possible inclusion of these features in usegalaxy.eu or so?

### CODE REVIEW

**Comment by volodymyrss** [comment]
@francoismg should we add a more colorful picture, since colormaps is one of the points?..

**Comment by bgruening** [comment]
If you like you can add that this will be available on all major galaxy server in version 23.1.

On EU we will also deploy your upcoming tools.
Thanks for creating the post!

**Comment by volodymyrss** [comment]
> > @francoismg should we add a more colorful picture, since colormaps is one of the points?..
> 
> yes no problem, do you have a specific colormap in mind or any will do?

oh because I wanted to set scale and so I just added one.

**Comment by volodymyrss** [comment]
I think, in principles

> If you like you can add that this will be available on all major galaxy server in version 23.1.
> 
> On EU we will also deploy your upcoming tools. Thanks for creating the post!

Ok, added! Fixed title quotation.

Please have a look if this all makes sense, we already agreed on the content in essence it internally, but we are open for any suggestions!

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Very cool. @yvanlebras already saw this PR and said he talked last week to astronomers from France. He said they also talked at FITS and the Vis ... so this blog post already spawned some interest before merging :)

**Comment by volodymyrss** [comment]
Thanks to @francoismg for implementing most of these two PRs!
 
Also it was possible because of the impressive progress made especially in the last years by [CDS](https://aladin.cds.unistra.fr) on https://github.com/cds-astro/aladin-lite which made it even more useful for many of our [use cases](https://github.com/cds-astro/aladin-lite/issues/10).

Following @leandro-liborio request for more information about our developments, I made a short preliminary [demonstration](https://youtu.be/R93jMdDNhfQ)  of our early-stage work (it also shows some simple astrotools), it shows this plugin too.

**Comment by bgruening** [comment]
Oh gosh this is cool! @volodymyrss if you want to add your thanks to CDS to the post as well, please do so!

> Following @leandro-liborio request for more information about our developments, I made a short preliminary [demonstration](https://youtu.be/R93jMdDNhfQ) of our early-stage work (it also shows some simple astrotools), it shows this plugin too.

I think this should also go into a blog post. Is a great demo, but maybe we do that after we have finished the tools and put it on EU?

**Comment by volodymyrss** [comment]
> Oh gosh this is cool! @volodymyrss if you want to add your thanks to CDS to the post as well, please do so!

Ok, yes, we already referred to them, but I now add explicit thanks too in https://github.com/galaxyproject/galaxy-hub/pull/2049/.
 
> > Following @leandro-liborio request for more information about our developments, I made a short preliminary [demonstration](https://youtu.be/R93jMdDNhfQ) of our early-stage work (it also shows some simple astrotools), it shows this plugin too.
> I think this should also go into a blog post. Is a great demo, but maybe we do that after we have finished the tools and put it on EU?

Sounds good!

**Pull request merged**
