### PR TITLE
Remove linkbox

### PR DESCRIPTION
**Pull request by jennaj**
Page could be expanded with graphics showing how the different sections of a tool form are structured.

### CODE REVIEW

**Comment by martenson** [comment]
@jennaj have a look at https://github.com/galaxyproject/galaxy-hub/issues/171

**Comment by martenson** [comment]
@jennaj This PR add no change to the code, just deleted and added an empty line. See the `Files changed` tab in the github PR interface.

**Comment by jennaj** [comment]
Odd - there was a conflict that I had to resolve and this is what came out of it.

**Comment by martenson** [comment]
That means you removed your changes while resolving the conflict.

**Pull request merged**
