### PR TITLE
Added scverse blogpost

### PR DESCRIPTION
**Pull request by SaimMomin12**
ping @bgruening

### CODE REVIEW

**Comment by pavanvidem** [comment]
I'm not sure we have copyrights to publish the conference group photo. Where did you get it from?

**Review by bgruening — COMMENTED** [review]
ok, from my side

**Comment by SaimMomin12** [comment]
> I'm not sure we have copyrights to publish the conference group photo. Where did you get it from? 

I think @nilchia shared it with me. In my opinion, it was shared on the scverse Zulip channel?

**Comment by nilchia** [comment]
Yes, it was shared on their Zulip channel. But now I am not sure if we can share it on Galaxy. We remove it then?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
