### PR TITLE
add Galaxy markdown tools blog entry

### PR DESCRIPTION
**Pull request by MingChen0919**
added a blog entry

### CODE REVIEW

**Comment by tnabtaf** [comment]
@MingChen0919 Any objection if I post this to the website next week?  The January news will go out  this week and I don't want this post to get lost in the noise of that.

**Comment by MingChen0919** [comment]
@tnabtaf no objection at all. Thanks for posting this!

**Comment by tnabtaf** [comment]
@MingChen0919 this will go out on Tuesday.  Thanks for your patience.

**Comment by tnabtaf** [comment]
@MingChen0919 post has been added.  Tweet will go out around 1pm Eastern on Tuesday.

**Pull request merged**
