### PR TITLE
place holder for sg2018

### PR DESCRIPTION
**Pull request by hrhotz**
will fill with more content over the next few months

### CODE REVIEW

**Comment by tnabtaf** [comment]
@hrhotz: Woohoo!  (Of course, I suspected as much, but it's good to see.)

Any chance I can convince you that 2018-sg would be a better directory name?  With the exception of GCC's, we've switched to putting dates first.

**Comment by hrhotz** [comment]
well, I just tried to be consistent, we have already ~/events/sg2014/, and ~/events/sg2016/, plus ~/events/switzerland2012/, /events/switzerland2014, and /events/switzerland2016 as well as ~/events/germany2014/ and ~/events/germany2016/.....
Since the base of the URL changed anyway (from wiki.galaxyproject.org/Events/ to galaxyproject.org/events/) it is probably a good time to change ?  ping @bgruening

**Comment by bgruening** [comment]
I'm ok with changing :) Thanks @hrhotz!

**Comment by hrhotz** [comment]
excuse my ignorance with git.....is there a simple way of changing the  directory name? Or shall I just drop this request and make a new one

**Comment by bgruening** [comment]
If you go to the edit button, you can change the filename, right? If you type backspace you can also change the dir name.

**Comment by hrhotz** [comment]
doh!  it is just a commit on the branch itself  doh!
 @bgruening  thank you for the pointer

**Comment by hrhotz** [comment]
shall I merge...in order to make the url from the logo functional?

**Comment by tnabtaf** [comment]
Thanks @hrhotz. Should show up shortly.

**Pull request merged**
