### PR TITLE
Process tweaks

### PR DESCRIPTION
**Pull request by dannon**
@clements In addition to a few build process tweaks, this will swap the default of autotoc: true.

It also prevents autotoc'ing on news and events page (where we do not render a toc anyway), saving some build time.

### CODE REVIEW

**Comment by martenson** [comment]
We might want to put a note into readme that you can use `autotoc:false` to disable it. Or is that not supported?

**Comment by dannon** [comment]
@martenson Yes, it's supported to set `autotoc: false` to disable it.  It's a good idea to document *all* the special metadata (news, events, general, etc) somewhere, agreed.

**Comment by martenson** [comment]
@dannon I started it here: https://github.com/galaxyproject/galaxy-hub/commit/1aa4e7ff34a77c24726543a57eafdd40582f40da

**Comment by dannon** [comment]
@martenson Thanks

**Comment by jbclements** [comment]
I hear from you guys a lot. I'm @clements :). How's it going?

**Comment by dannon** [comment]
@jbclements It's going well, sorry for the noise!  I meant @tnabtaf :(

**Comment by jbclements** [comment]
No problem! Hope things are going well.

Best from San Luis Obispo,

John

**Pull request merged**
