### PR TITLE
Naming standardization

### PR DESCRIPTION
**Pull request by dannon**
xref #39 , #36

### CODE REVIEW

**Comment by dannon** [comment]
@tnabtaf Let me know what you think.

**Comment by tnabtaf** [comment]
Yow!

Is what I think.  I'll take a detailed look (and learn PR processing) this weekend (i'm at PAG) with the goal of having this reviewed and in by Sunday night.

**Comment by bgruening** [comment]
list of broken links:
* http://localhost:8080/Develop/BestPractices is broken.
* http://localhost:8080/Develop/SourceDoc all links under http://localhost:8080/admin/ seem to be broken.
* http://localhost:8080/Admin/Tools/AddToolFromToolShedTutorial
* http://localhost:8080/IUC

**Comment by dannon** [comment]
I'm working on updating this branch with recent changes and fixing a few links.  @tnabtaf Think we can merge this after that and work forward?  Because of all the moved files, it's going to be very cumbersome to keep up to date.

**Comment by tnabtaf** [comment]
@dannon I'm in favor of getting the renaming in as soon as possible.  Delaying would lead to insanity.

**Comment by dannon** [comment]
Ok.  I'm going to get the branch up to date, fix the obvious broken links, and then merge it today to avoid any more divergence.  I'll continue to follow up on 'make check' broken link report after, and fix issues as they arise.

**Comment by dannon** [comment]
Merging, fixing more links in followup.

**Comment by tnabtaf** [comment]
Woot!

**Comment by bgruening** [comment]
Nice, thanks @dannon!

**Pull request merged**
