### PR TITLE
Add Github Action to optimize all images automatically

### PR DESCRIPTION
**Pull request by davelopez**
Hi!
We have just [tested this action](https://github.com/usegalaxy-eu/website/pull/662) on the EU website and seems to work quite well, see the result [here](https://github.com/usegalaxy-eu/website/pull/663).

I've made this PR in case you want to use it too :)

The first time it runs will probably create a PR with lots of updated images, and then it will only update when there are new images that can be optimized as part of a PR or periodically every Sunday at 11 PM.

Hope it helps!

### CODE REVIEW

**Comment by dannon** [comment]
@davelopez Great idea!  Thanks, let's see how it goes.

**Comment by bgruening** [comment]
Uh does this work with git-lfs?

**Comment by davelopez** [comment]
I hope so 😅 we will see when someone runs it manually or in the next PR with images on it.

**Comment by dannon** [comment]
Good question, I didn't even think about LFS.  If it blows up, I guess we'll know :)

**Pull request merged**
