### PR TITLE
Ocean data view news

### PR DESCRIPTION
**Pull request by Marie59**
I did a little news on ODV. Maybe it's a bit early and we should wait for the tuto ? not sure. This is my last one for a bit of time normally ;)

### CODE REVIEW

**Comment by Marie59** [comment]
@bgruening Do you know why there is this Gitpod test ?

**Comment by dannon** [comment]
@Marie59 You can disregard that.  I was working on adding a link to PRs to make it easier for folks to explore gitpod, but PRs from forks need the permissions tweaked to work -- I think I will probably just remove it and we can add instructions in the README instead.

**Comment by Marie59** [comment]
Great thanks a lot @dannon !

**Comment by bgruening** [comment]
@Marie59 is this one ready to go or to you want o wait for the training?

**Comment by Marie59** [comment]
> @Marie59 is this one ready to go or to you want o wait for the training?

I think it's ready we may not need to wait for the training

**Pull request merged**
