### PR TITLE
Rewrote multiple outputs docs

### PR DESCRIPTION
**Pull request by erasche**
Based on a coworkers comments that is wasn't very clear.

- Fixed a couple of broken links.
- Remove unnecessary verbiage / unstructured repetition
- Changed section headings to simplify document

### CODE REVIEW

**Comment by jmchilton** [comment]
This is frustrating and seemingly entirely my fault - I'm sorry. I moved these docs to http://planemo.readthedocs.io/en/latest/writing_advanced.html#multiple-output-files. I don't know why I didn't update the wiki. Feel free to merge this here - and I can walk through and try to port your changes to planemo - but at some point I want to remove this page and link out to planemo's variant of these docs.

**Comment by erasche** [comment]
Oh, hey, neat! :) That looks a *lot* better than what I have, I'd rather just update this PR with a link to planemo docs. I even went looking in planemo's docs for collection stuff and it wasn't where I thought so I quit looking ahah. Please, no worries @jmchilton, didn't take a lot of my time. I'll update this tomorrow pointing to planemo's.

**Comment by dannon** [comment]
(merging, we can update more with pointers to other docs and/or transclude later)

**Comment by martenson** [comment]
@dannon I think the author of this PR said he will update it. Seems premature merging it.

**Comment by dannon** [comment]
@martenson It can always be updated more.  As it is, this is a big step forward and it had been sitting for over a week.  Incremental improvement is still good!

**Comment by erasche** [comment]
Oh, no this is totally fine, sorry, I got distracted.

**Comment by erasche** [comment]
Added an issue linking this, in case anyone has a good solution / wishes to tackle it.

**Comment by dannon** [comment]
@erasche Cool, thanks!

**Pull request merged**
