### PR TITLE
EuroScienceGateway/wp5/Astronomy news

### PR DESCRIPTION
**Pull request by volodymyrss**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @volodymyrss for working on this!

**Comment by volodymyrss** [comment]
> Thanks @volodymyrss for working on this!

We edited it a bit more with @andriineronov . I'll do just a bit more and mark it as ready.

**Comment by volodymyrss** [comment]
I am not too sure if we should keep external link to the image or put it in assets, I do not know how big you want the assets to be. The link could be also changed to something more permanent.

**Comment by volodymyrss** [comment]
I updated text and put an illustratory picture

image

**Comment by bgruening** [comment]
Thanks a lot!

**Comment by volodymyrss** [comment]
> Thanks a lot!

Thank you! I can see it now https://galaxyproject.org/news/2022-12-12-esg-wp5-astronomy/ . 

We'll post the reference in our news.

**Comment by bgruening** [comment]
Cool! Merci!

**Pull request merged**
