### PR TITLE
Update ObjectStore documentation, and add GCE backend docs.

### PR DESCRIPTION
**Pull request by VJalili**

### CODE REVIEW

**Comment by dannon** [comment]
@VJalili Can you use git-lfs for the binary files?  (more info at https://github.com/galaxyproject/galaxy-hub/blob/master/CONTRIBUTING.md#setup, or ping me for more help)

**Comment by VJalili** [comment]
@dannon images are updated as you recommended.

**Comment by dannon** [comment]
@VJalili Thanks!  And thanks for the updates.  I'm going to push a few fixes after, but I'll go ahead and merge this.

**Comment by VJalili** [comment]
Sound good, thanks.

**Pull request merged**
