### PR TITLE
Update datacache info for CVMFS and HTTP

### PR DESCRIPTION
**Pull request by natefoo**
This should probably move to a different page name and redirect?

### CODE REVIEW

**Comment by tnabtaf** [comment]
@natefoo Any suggestions on what the new page path should be?  Content looks good.

**Comment by bgruening** [comment]
Super cool!

**Comment by martenson** [comment]
@tnabtaf `datacache/index.md`?

**Comment by natefoo** [comment]
Could also be `reference_data`?

**Comment by natefoo** [comment]
I am not sure how to configure [metalsmith-alias](https://www.npmjs.com/package/metalsmith-alias) to do the redirect. I can just put a static redirection page there though if that's preferable.

**Pull request merged**
