### PR TITLE
major revision of histories tutorial with addition of tags and name t…

### PR DESCRIPTION
**Pull request by nekrut**
…ags discussion

### CODE REVIEW

**Comment by dannon** [comment]
(made a few minor tweaks, following up with just a bit more in a sec)

**Comment by dannon** [comment]
Looks nice!  Should we call 'nametags' 'hashtags' more formally?

**Comment by nekrut** [comment]
Ok. I'll change them to hashtags

**Comment by dannon** [comment]
Hey, you named it :)  I do like it though.

**Comment by dannon** [comment]
@nekrut Thanks!

**Pull request merged**
