### PR TITLE
user information

### PR DESCRIPTION
**Pull request by bgruening**
* images are missing
* /src/admin/interface seems to be missing (@martenson do you know if this was on purpose?)

### CODE REVIEW

**Comment by martenson** [comment]
yes, `/src/admin/interface` removed on purpose

**Comment by martenson** [comment]
also `images` are not missing, they are just not listed: https://github.com/galaxyproject/galaxy-hub/tree/master/src/images

**Comment by bgruening** [comment]
@martenson what do you mean with not listed? it seems the `user_registration.png` is missing in this repo.

**Comment by martenson** [comment]
What I mean is that https://galaxyproject.org/images/ does not list the contents of https://github.com/galaxyproject/galaxy-hub/tree/master/src/images as old wiki did.

That file seems missing, we need to copy it over from moin and add to hub.

**Comment by bgruening** [comment]
Ok, this is what I meant for most of the images that are referenced in this page.

**Comment by erasche** [comment]
rebased @bgruening. I've got the images in another WIP branch. I'll merge those in later.

**Comment by bgruening** [comment]
Upps, totally forgot about this one. Thanks.

**Pull request merged**
