### PR TITLE
Act dont criminalize

### PR DESCRIPTION
**Pull request by wm75**
@bgruening I've included you as an author so make you agree with the wording, and ask for changes where you don't :)

### CODE REVIEW

**Comment by bgruening** [comment]
@wm75 with the new website we need to update the notice here: `content/bare/eu/usegalaxy/notices.md`

**Review by bgruening — APPROVED** [review]
Thanks @wm75! Let's make some fuzz about it.

**Comment by wm75** [comment]
> @wm75 with the new website we need to update the notice here: `content/bare/eu/usegalaxy/notices.md`

Ah, I see! Will do.

**Comment by wm75** [comment]
Hope it'll work like this.

**Pull request merged**
