### PR TITLE
Move "distancing badge" section to conduct page

### PR DESCRIPTION
**Pull request by neoformit**
Requested by Gareth

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
Thanks @GarethPrice-Aus for the clarity

**Comment by GarethPrice-Aus** [comment]
Hi @hexylena, sorry I don't understand the " :( " comment.  This request was in response to your email dated Friday 30th June - "Will you be moving the lanyard information away from the covid page to another page more appropriate so it doesn't have that confusing "this is a covid prevention measure" feeling?"
Another communication will be issued regarding the stance of the organising committee on mask wearing at GCC2023

**Comment by hexylena** [comment]
sounds good @GarethPrice-Aus !

**Comment by hexylena** [comment]
and you're right @GarethPrice-Aus the emoticon wasn't necessary, I'm just one of those millenials that is very transparent about their emotional state. Simply an expression of my feelings over the past five weeks since we began the topic, but you're right not relevant to the PR at hand. I'll remove it accordingly

**Comment by GarethPrice-Aus** [comment]
I'll do the same and we can just re-write this bit of history

**Pull request merged**
