### PR TITLE
Update Carousel.vue to remove "Colabfold Coming Soon"

### PR DESCRIPTION
**Pull request by natwhitaker**
Removing the image advertising that Colabfold is 'coming soon'.

### CODE REVIEW

**Comment by dannon** [comment]
@natwhitaker Still want to make this change?

**Comment by natwhitaker** [comment]
@dannon Ahh whoops, yes! This completely slipped my mind.

**Comment by natwhitaker** [comment]
> @natwhitaker Still want to make this change?

@dannon Okay, I'm sorry to bother you with something so simple, but I cannot figure out why this failed. All I did was remove the section with the ColabFold image. I've gone back and looked at the current code to see where I'm missing something it, and all the rest matches up. Maybe I'm being blind? Again, sorry to have to ask.

**Comment by dannon** [comment]
@natwhitaker Looks fine to me.  I don't remember the timing exactly, but this may have failed when plausible was down based on the test output -- I've rebased and it should pass now.

**Comment by natwhitaker** [comment]
@dannon Ah, okay! Thanks so much, I thought I was going crazy.

**Pull request merged**
