### PR TITLE
EU banner update: replace call for trainers banner with GTA user registration banner

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**
FYI: @teresa-m

### CODE REVIEW

**Comment by sanjaysrikakulam** [comment]
@dannon The [GA](https://github.com/galaxyproject/galaxy-hub/actions/runs/10716985642/job/29715692912?pr=2754) is failing with the error

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more at https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/.
```
Could you please look into this?

**Comment by dannon** [comment]
@sanjaysrikakulam Yep!  Looks like they finally pulled the plug on that one.  Checking it out.

**Comment by sanjaysrikakulam** [comment]
> @sanjaysrikakulam Yep! Looks like they finally pulled the plug on that one. Checking it out.

Cool! Thank you!

**Review by dannon — APPROVED** [review]
Upload action is fine now (updated to v4) and only affected the cypress tests, this should be good to go but you are welcome to rebase if you want a clean test rerun.

**Comment by sanjaysrikakulam** [comment]
> Upload action is fine now (updated to v4) and only affected the cypress tests, this should be good to go but you are welcome to rebase if you want a clean test rerun.

Thank you! :)

**Comment by teresa-m** [comment]
Thanks to all of you!

**Pull request merged**
