### PR TITLE
Add GCC2023 logo and attendee numbers

### PR DESCRIPTION
**Pull request by PatCapon39**
@GarethPrice-Aus here's the GCC2023 logo plus attendee numbers - I couldn't preview the size, so that might need tweaking

### CODE REVIEW

**Comment by GarethPrice-Aus** [comment]
@afgane @PratikDJagtap 
Hi Enis and Pratik, Patrick is doing some updates to GCC page, mostly for 2023. We want to add the 23 logo but that means 22 will look obvious in missing. Can you add one from: https://github.com/galaxyproject/galaxy-hub/tree/master/content/images/events/gcc2022 to the page also?

**Comment by afgane** [comment]
Did we have an official logo for GCC2022? All I can find is that picture of the Minneapolis skyline but we used that more as a banner than a logo.

**Comment by martenson** [comment]
I believe 22 can be added at any time later

**Comment by PratikDJagtap** [comment]
We had this one as a placeholder. It is also on the website.


[image: image.png]


@pratikomics on BlueSky, Mastodon, Threads and X.

Google Scholar: z.umn.edu/pjgs



http://galaxyp.org

**Comment by martenson** [comment]
@PratikDJagtap I suspect github does not process email attachments, would you mind posting it directly at the issue? (https://github.com/galaxyproject/galaxy-hub/pull/2481)

**Pull request merged**
